[package]
name = "naia-hecs-server"
# 0.22 is unpublished for now, due to lack of use of this crate, as well as plans for rapid releases - 1/9/2024
version = "0.22.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
description = "Library to faciliate naia_server & Hecs interop"
homepage = "https://github.com/naia-lib/naia"
repository = "https://github.com/naia-lib/naia"
keywords = ["wasm", "webrtc", "udp", "networking", "gamedev"]
categories = ["network-programming", "game-development", "wasm", "web-programming"]
license = "MIT OR Apache-2.0"
edition = "2021"

[badges]
maintenance = { status = "actively-developed" }

[features]
transport_webrtc = [ "naia-server/transport_webrtc" ]
transport_udp = [ "naia-server/transport_udp" ]

[dependencies]
naia-server = { version = "0.22", path = "../../../server" }
naia-hecs-shared = { version = "0.22", path = "../shared" }
hecs = { version = "0.10" }